# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='fridayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='fridayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='mondayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='mondayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='saterdayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='saterdayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='sundayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='sundayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='thursdayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='thursdayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tuesdayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tuesdayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='wednesdayAvailabilityEndTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='wednesdayAvailabilityStartTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shiftName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
